@extends('pages.layout.app')
@section('content')


    <div class="page-title-section" style="background-image: url(front/img/bg/pagetitle.jpg);">
        <div class="container">
            <h1>Terms & Conditions</h1>
            <ul>
                <li><a href="{{ route('homepage') }}">Home</a></li>
                <li><a href="{{ route('faq') }}">Terms & Conditions</a></li>
            </ul>
        </div>
    </div>
    <div class="section-block">
        <div class="container">
            <div class="section-heading">
                <h4>Terms & Conditions</h4>
                <div class="section-heading-line-left"></div>
            </div>
            <div class="row mt-40">
                <div class="col-md-12 col-sm-12 col-12">
                    <header class="crumina-module crumina-heading heading--h2 heading--with-decoration">
                        <div class="heading-sup-title">Comearners investment Account Terms of Use
                        </div>
                        <p>[Version - January, 2021]</p>
                    </header>


                    <h4>1. About Comearners Investment Company</h4>
                    <p style="font-size: 20px"> 1.1. Comearners® is a trading name of Comearners investment Limited, a company incorporated under the laws of England and Wales with registration number 4260907762. We are authorized by the Financial Conduct Authority (FCA) under the Electronic Money Regulations 2011 for the issuance of electronic money. Our FCA e-money register number is 9000701.</p>

                    <h4>2. Scope of these Terms of Use</h4>
                    <p style="font-size: 20px"> 2.1. These Terms of Use govern the opening, use and closure of your Comearners® Account and other related payment services as referred to herein. Together with any other terms and conditions referred to in these Terms of Use, they constitute the agreement between you and us. For the use of additional services you may have to accept additional terms and conditions as notified to you when you are ordering or using such services. You are advised to print or download and keep a copy of these Terms of Use for future reference. You can always view the current Terms of Use on our Website.</p>
                    <p style="font-size: 20px"> 2.2. Depending on the type of Comearners mining Account you have, additional terms and conditions may apply as communicated to you at the appropriate time. In the event of any conflict between the additional terms and conditions and these Terms of Use, the former shall come first.</p>

                    <h4>3. Your Comearners Investment trading Account</h4>
                    <p style="font-size: 20px">3.1. Your Comearners Account is an electronic/digital cryptocurrency Tradings account which enables you to Invest, mine, send and receive electronic payments from your personal Crypto currency wallet into your mining account.
                    </p>
                    <p style="font-size: 20px">3.2. Your Comearners Account is denominated in any Crypto currency of your choice, as selected by you from the market Capitalization which is made available from time to time. This will remain the currency of your Comearners Account for the duration of your agreement with us as specified by you.</p>
                    <p style="font-size: 20px">3.3. Subject to section 7, the electronic/digital crypto currency held on your Comearners Account does not expire but it may stop Trading to profits you more interesting profits once you are not an active Investor</p>
                    <p style="font-size: 20px">3.4. You have the right to withdraw funds from your Comearners Account at any time. However, you may be required to confirm your identity onwards or require to complete your Standard Know Your Client (KYC). There is NO minimum withdrawals amount but the funds on your Comearners Account must be sufficient to cover any applicable withdrawal fee if necessary. You can choose the method of withdrawal when submitting your withdrawal request as you provided your payment details depending on your preference.</p>
                    <p style="font-size: 20px">3.5. Electronic/Digital crypto currency wallets accounts are not bank accounts. By accepting these Terms of Use you acknowledge that the UK’s Financial Services Compensation Scheme (FSCS) does not apply to your Comearners Account. In the unlikely event that we become insolvent, you may lose the electronic money held in your Comearners Account. However, the European Electronic Money Directive 2009/110/EC and UK national legislation apply to us and these are designed to ensure the safety and liquidity of funds deposited in your crypto currency Comearners accounts.</p>
                    <p style="font-size: 20px">3.6. The electronic money on an Comearners Account belongs to the person or legal entity which is registered as the Comearners Account holder. No person other than the Comearners Account holder has any rights in relation to the funds held in an Comearners Account, except in cases of succession and Next of Kim, You may not assign or transfer your Comearners Account to a third party or otherwise grant any third party a legal or equitable interest over it.</p>
                    <p style="font-size: 20px">3.7. Your Comearners Account may be subject to upload, payment and withdrawal limits, depending on your country of residence, the verification status of your Comearners Account and other factors used by us to determine such limits from time to time at our sole discretion.</p>

                    <h4>4. Opening Your Comearners Investment Account</h4>
                    <p style="font-size: 20px">4.1. In order to use our Investment Financial payment services you must first open an Comearners Investment Account by registering your details on our Website and also Joining the official telegram group. As part of the signup process you will need to accept these Terms of Use and our Privacy Notice and you must have legal capacity to accept the same. If you order additional services, you may be asked to accept additional terms and conditions.</p>
                    <p style="font-size: 20px">4.2. If you are an individual, you must be 18 years or older to use our services and by opening an Comearners Investment Account you declare that you are 18 years or older. This does not apply to products for which we set a different age limit. We may require at any time that you provide evidence of your age.</p>
                    <p style="font-size: 20px">4.3. You may only open one Comearners Account unless we explicitly approve the opening of additional accounts.</p>
                    <p style="font-size: 20px">4.4. You may only open an Comearners Account,As it is legal to do so in all countries of residence where Crypto currency is accepted. By opening an Comearners Account you represent and warrant to us that your opening of a Comearners Investment Account does not violate any laws or regulations applicable to you. You shall pay us the amount of any losses we incur in connection with your breach of this section.</p>
                    <p style="font-size: 20px">4.5. All information you provide during the signup process or any time thereafter must be accurate and truthful. If you do not provide such information or cooperate as instructed by us within Three(3) months of opening your Comearners Investment Account or within such other deadline as we may notify to you at any time thereafter we may charge you an administration fee as displayed in the "Fees" section of the Website or through the 24/7 Live chat support team.</p>
                    <p style="font-size: 20px">4.6. You may only add Payment Methods of a complete verified Blockchain technology crypto currency wallet to your Comearners Account if you are the named holder of the Cryptocurrency wallet provided for that Payment Method. We take any violation of this requirement very seriously and will treat any attempt to add a Payment Wallet Method of which you are not the named holder or verified by yourself as a fraudulent act.</p>
                    <p style="font-size: 20px">4.7. During signup you will be asked whether you intend to use your Comearners Investment Account for private or commercial purposes. If you have any intention to use your Comearners Investment Account for commercial purposes, you must tell us, even if you use it also for private purposes. If you have stated that you will use your Comearners Investment Account for private purposes only, you must tell us immediately before, at any point in the future you use it for commercial purposes by contacting Customer Care Service. You are using your Comearners Investment Account for commercial purposes if you choose to make Investment progress for or in connection with any business activity. We reserve the right to determine whether, in our reasonable opinion, you are using your Comearners Investment Account for commercial purposes. If you are using your Comearners Account for commercial purposes, in addition to these Terms of Use, you shall be bound by our Merchant Terms and Conditions. If you are in any doubt about whether or not an activity amounts to a commercial activity, you should contact Customer Service.</p>
                    <p style="font-size: 20px">4.8. Within 14 days of the date of opening your Comearners Investment Account make your Comearners Investment Account Active by making a decided deposit or you may be forced close your Comearners Investment Account at no cost by contacting Customer Service, however if your account is dormant for 14days it will be deleted and diactivated , if you have uploaded funds into your Comearners Account, you may be required to provide identification documents before being able to withdraw Investment funds. Transactions and fees for transactions undertaken before you close your Comearners Investment Account (including those transactions that are not revocable and have been initiated but not completed before closure of your Comearners Account) will not be refunded.</p>

                    <h4>5. Maintaining Your Comearners Investment Account</h4>
                    <p style="font-size: 20px">5.1. You must ensure that the information recorded on your Comearners Investment Account is always accurate and up to date and we shall not be liable for any losses arising out of your failure to do so. We may ask you at any time to confirm the accuracy of your information or to provide documents or other evidence as you continue to make your crypto currency investment growth</p>
                    <p style="font-size: 20px">5.2. We may contact you by e-mail or in any other ways described in section 18 with information or notices regarding your Comearners Investment Account. It is your responsibility to regularly checking the proper functioning of your e­mail account or other methods of communication that you have registered with your Comearners Account and to retrieve and read messages relating to your Comearners Account promptly. We shall not be liable for any losses arising out of your failure to do so.</p>
                    <p style="font-size: 20px">5.3. Investment Fund uploads, payments received, payments sent and fund withdrawals are displayed in your online transactions histories together with the date of receipt or transmission (the debit/credit value date), the fees charged and, where applicable, any exchange rate used. Each transaction is given a unique transaction ID and shown in the transaction history. We will not alter or amend information displayed in your online transaction history. You should quote this transaction ID when communicating with us about a particular transaction. You should check your Comearners Investment Account balance and transaction history regularly. You should report any irregularities or clarify any questions you have as soon as possible by contacting Customer Care Service.</p>
                    <p style="font-size: 20px">5.4. We will send you an e-mail notification to the e-mail address used when registering for your Investment Account (as updated from time to time by you) every day reminding you to log into your Comearners Investment Account and download and/or print a copy of your transaction history.</p>
                    <p style="font-size: 20px">5.5. Subject to the provisions of section 8 below and without prejudice to the provisions of section 9.5(A), in order to claim a refund for an unauthorized or incorrectly executed payment transaction on your Comearners Investment Account you must notify us without undue delay after becoming aware of the unauthorized or incorrect transaction and in any event no later than one(1)hour after the debit/withdrawal time of the transaction.</p>

                    <h4>6. Keeping Your Comearners Investment Account Safe</h4>
                    <p style="font-size: 20px">6.1. You must take all reasonable steps to keep your Comearners Investment Account password and any other security features safe at all times and never disclose them to anyone. Our personnel will never ask you to provide your password to us or to a third party. Any message you receive or website you visit that asks for your password or other security features, other than the Comearners Investment Website or an Comearners  Investment payment gateway on a merchant website like Blockchain,Luno,trust, binance, Coinph, Coinmama, PAXFUL, Localbitcoin and all other Crypto currency wallet address the is used by you, should be reported to us. If you are in doubt whether a website is genuine, you should contact Customer Care Service through our company's support email support@airlinetrades.com or contact the 24/7 live chat support team. It is advisable to change your password regularly (at least every one(1) to two (2) months) in order to reduce the risk of a security breach in relation to your Comearners Account. We also advise you not to choose a password that is easily guessed from information someone might know or gather about you or a password that has a meaning. Except as stated in section 9.A, you must never allow anyone to access your Comearners Investment Account or watch you accessing your Comearners Investment Account. You must comply with the security procedures we tell you about from time to time.</p>
                    <p style="font-size: 20px">6.2. If you have any indication or suspicion of your Comearners Investment Account, login details, password or other security feature being lost, stolen, misappropriated, used without authorisation or otherwise compromised, you are advised to change your password. You must contact Customer Care Service without undue delay on becoming aware of any loss, theft, misappropriation or unauthorized use of your Comearners Investment Account, login details, password or other security features. Any undue delay in notifying us may not only affect the security of your Comearners Investment Account but may result in you being liable for any losses as a result where your failure to notify us is intentional or grossly negligent. If you suspect that your Comearners Investment Account was accessed by someone else, you should also contact the police and report the incident to us</p>
                    <p style="font-size: 20px">6.3. We may suspend your Comearners  Investment Account or otherwise restrict its functionality on reasonable grounds relating to the security of the Comearners Account or any of its security features or if we reasonably suspect that unauthorized or fraudulent use of your Comearners Investment Account has occurred or that any of its security features have been compromised. We will notify you of any suspension or restriction and of the reasons for such suspension or restriction in advance or, where we are unable to do so, immediately after the suspension or restriction has been imposed, unless notifying you would be unlawful or compromise our reasonable security interests. We will lift the suspension and/or the restriction as soon as practicable after the reasons for the suspension and/or restriction have ceased to exist.</p>
                    <p style="font-size: 20px">6.4. If we think your Comearners Investment Account is at risk of fraud or a security threat, we will use the fastest and most secure way of contacting you using the details you have provided to tell you what you need to do to help deal with that risk.</p>
                    <p style="font-size: 20px">6.5. You must take all reasonable care to ensure that your e-mail account(s) are secured and only accessed by you, as your e-mail address may be used to reset passwords or to communicate with you about the security of your Comearners Investment Account. In case any of the e-mail addresses registered with your Comearners Accounts are compromised, you should without undue delay after becoming aware of this contact Customer Care Service and also contact your e-mail service provider.</p>
                    <p style="font-size: 20px">6.6. Irrespective of whether you are using a public, a shared or your own computer to access your Comearners Account, you must always ensure that your login details are not stored by the browser or cached or otherwise recorded. You should never use any functionality that allows login details or passwords to be stored by the computer you are using.</p>
                    <p style="font-size: 20px">6.7. Additional products or services you use may have additional security requirements and you must familiarise yourself with those as notified to you.</p>

                    <h4>7. Closing Your Comearners Investment Account</h4>
                    <p style="font-size: 20px">7.1. You may close your Comearners Account at any time by contacting Customer Care Service. Fees relating to ongoing management of inactive accounts will also continue to be charged following closure of your Account. This provision shall survive termination of the relationship between you and us.</p>
                    <p style="font-size: 20px">7.2. If your Comearners Investment Account holds a balance at the time of its closure, we will ask you to withdraw your funds within a reasonable period of time, during which your Comearners Account will be accessible for the purpose of withdrawing the remaining balance only. After the expiry of this period you will not be able to access your Comearners Investment Account but you may withdraw any remaining funds by contacting Customer Care Service and requesting that the Investment funds are sent to you in a manner that is reasonably acceptable for us. If you want to access your transaction history after the closure of your Comearners Account, you will need to contact Customer Care Service and request the information, You may do so for a period of one years from the date of closure of your Comearners Account but we suggest that you withdraw your remaining funds as soon as possible as they will not be earning any interest while in your dormant Comearners Investment Account. Your obligations with regards to keeping your Comearners Account safe as set forth in section 6 shall continue to apply.</p>
                    <p style="font-size: 20px">7.3. We reserve the right to carry out any necessary money laundering, terrorism financing, fraud or other illegal activities checks before authorizing any withdrawal of your investment funds, including in relation to returning any Investment funds to you after you have closed your Comearners Account.</p>

                    <h4>8. Uploading Investment Funds</h4>
                    <p style="font-size: 20px">8.1. You can upload funds by visiting the Website, logging into your Comearners Investment Account and following the relevant upload instructions to enable you start up an investment package,or can easily follow the process Step by Step</p>
                    <p style="font-size: 20px">How to create a successful deposit</p>
                    <ol>
                        <li>Log in your Comearners Investment account, On your dashboard, Click on "Make Deposit"</li>
                        <li>Select on your preferred Investment plan</li>
                        <li>Enter your correct actual deposited amount you wish to recycle</li>
                        <li>Click on Spend</li>
                        <li>A Transaction Details will appear, Choose your preferred method of payment either Bitcion or Ethereum Wallet address respectively or Ask the company live chat for any other crypto currency wallet you wish to inject your investment capital and then send the equivalent amount into the company's mining wallet.</li>
                        <li>Then go to your personal crypto currency exchanger/ wallet and send and upload a screenshot prove of your transaction with the correct wallet and Hashtag prove.</li>
                    </ol>
                    <p style="font-size: 20px">Note that once you upload the transactions prove your deposit has been instantly saved, wait for the company to approve it immediately or contact the us</p>
                    <p style="font-size: 20px"> You may be presented with a number of different upload methods, depending on which Payment Methods you have added to your Comearners Investment Account and which Payment Methods are available in your country of residence. Upload methods are payment services provided by third party financial institutions (for example, the issuer of the payment card you use to upload funds or third party direct banking service providers) and are not part of our service. We do not guarantee the use of any particular upload method made available, and may make changes to or discontinue the acceptance of any particular upload method at any time without following the procedure set out in section 17. Notwithstanding section 8.7 below, we shall not be responsible for the upload payment until the uploaded funds are received by us.</p>
                    <p style="font-size: 20px">8.2. You may be asked to answer security questions or to complete other activities that we or the Cryptocurrency payment service provider you use to upload funds to your Comearners Investment Account may reasonably require to ensure proper authorisation of an upload transaction.</p>
                    <p style="font-size: 20px">8.3. If you choose to upload funds using a Payment Method that may be subject to a right to claim funds back (a "Chargeback") such as (but not limited to) credit or debit card or direct debit, you declare that you will not exercise such Chargeback other than for unauthorized use of the Payment Method or for a breach by us of these Terms of Use which would result in you having a right to a refund of the uploaded amount. Otherwise, you may not Chargeback any upload transaction or allow Chargeback of any upload transaction for reasons for which we are not responsible including (but not limited to) disputes with merchants for non-delivery of goods or services or insufficient balance on the wallet Payment Method account. We reserve the right to charge you fees and expenses we incur in connection with such Chargeback and any action undertaken to challenge the same. We may also charge you a Chargeback fee as displayed in the "Fees" section of the Website.</p>
                    <p style="font-size: 20px">8.4. You may allow a merchant that you wish to pay through us on a regular basis (e.g. for a subscription service) to debit your Comearners Investment Account for each recurring payment. In this case you authorise us to debit the Payment Method (e.g. your Blockchain or any other Crypto account) which you used to make the original payment also for each subsequent payment. In order to cancel recurring payments for the future, you should (a) contact us and (b) notify the merchant from which you have purchased the goods or services that you have cancelled the recurring payment. You should not cancel or otherwise reverse such recurring transactions by simply contacting the issuer / account provider of the Payment Method (e.g. your Blockchain technology) without following the cancellation steps mentioned in this section 8.4. Subject to section 8.5, we will not be liable for any recurring payment(s) that are made before you have notified us of the cancellation and if your Comearners Investment Account balance goes into negative balance as a result of such payment(s), you will be liable to repay such amount to us.</p>
                    <p style="font-size: 20px">
                        8.5. We will refund any past recurring payment(s) initiated by or through the merchant provided that (a) the original authorisation given to us or the merchant did not specify the exact amount of the payment and (b) the amount of the payment exceeded the amount that you could reasonably have expected taking into account your previous spending pattern and the circumstances of the case. You must request such a refund within eight weeks from the date the funds were debited from your Comearners Investment Account. You agree to provide us with such information as is reasonably necessary to ascertain whether the conditions for a refund described in this section 8.5 are satisfied. Within ten (10) Business Days of receiving a request for a refund or, where applicable, of receiving any further information we requested from you, we will either refund the full amount of the payment or provide you with justification for refusing to refund the payment indicating that you have a right to refer the matter to the Financial Ombudsman Service (details in section 21) if you do not accept the justification provided.</p>
                    <p style="font-size: 20px">8.6. If a chargeback or reversal of an upload transaction results in a negative balance in your Comearners Investment Account, you will be required to repay such negative balance by uploading sufficient funds into your Comearners Investment Account. Failure to do so is a breach of these Terms of Use. Repayment of the negative balance is due immediately without notice. We reserve the right, at any time, to send you reminders or to take other debt collection measures including but not limited to mandating a debt collection agency or solicitors or to pursue the claim in court. We reserve the right to charge you the expenses we reasonably incur in connection with any debt collection or enforcement efforts.</p>
                    <p style="font-size: 20px">8.7. Uploaded funds will be credited to your Comearners Investment Account after the funds have been received by us to commerce your Investment immediately and these will take 5-30mins of confirmation. Some upload transactions, such as those by credit or debit card, direct debit or direct banking and online banking will be credited to your Comearners Investment Account in 2-5 working days  but are subject to reversal if the actual funds do not reach us within a reasonable time in which case we will deduct such reversed transaction from the balance of your Comearners Investment Account. If your Comearners Investment Account balance is insufficient, we reserve the right to require repayment from you to enable your account be active for more Investment profits</p>
                    <p style="font-size: 20px">8.8. For the purposes of an upload transaction through a Payment Method, we are an e-money issuer and will issue e-money in exchange for the uploaded funds. We will not be acting as a payment service provider when receiving such funds.</p>
                    <p style="font-size: 20px">8.9. You must not make an upload through a Payment Method if you are not the named holder of that Payment Method. We take any violation of this requirement very seriously and will treat any attempt to use a Payment Method of which you are not the named holder as a fraudulent act.</p>
                    <p style="font-size: 20px">8.10. Uploads may be subject to upload limits due to security and legal requirements. These limits are set dynamically depending on your verification status and the upload method you want to use. You should be aware that depending on your verification status your upload limits may be higher than your withdrawal or spending limits. You can view these limits at any time in the relevant section of your Comearners InvestmentAccount profile.</p>
                    <p style="font-size: 20px">8.11. Uploads are subject to fees including Cryptocurrency charges of both parties fees (if applicable). Please see section 13 for details.</p>
                    <p style="font-size: 20px">8.12. You must not make an upload using cash. Without prejudice to claiming further damages, if we are required to take any action on your Comearners Investment Account as a result of you making a cash upload, we may charge an administration fee as displayed in the "Fees" section of the Website.</p>


                    <h4>9. Sending Payments</h4>
                    <p style="font-size: 20px">9.1. To send a deposit or withdrawal you are required to authorize the payment with your login details and password. We may also ask you additional security questions relating to you or your Comearners Investment Account. If your Comearners Investment Account is protected by additional security measures such as password tokens, you need to follow the instructions provided to you with such additional security measures. If your Comearners Investment Account is enabled to make mass payments, the procedure to make such payments will be communicated to you in the relevant integration manual.</p>
                    <p style="font-size: 20px">9.2. Every recipient of a payment you wish to send through us must have a valid means that we can use for their identification. For most of our services that means of identification will be a valid e-mail address but other means of identification may be required for our other services.</p>
                    <p style="font-size: 20px">9.3. If you are asked to provide details of the recipient’s e-mail address or other means of identification, where applicable, you must take great care to properly type the exact details of who you wish to send money to. We use those details as the unique identifier to determine the intended recipient of the payment which you instruct us to process. Other information you provide along with the recipient’s means of identification may be disregarded and we shall not be liable for any error you make when entering the recipient’s means of identification.</p>
                    <p style="font-size: 20px">9.4. If the correct e-mail address and crypto currency wallet of the intended recipient is registered with us, the funds will be instantly credited to the Comearners Investment Account associated with that e-mail address and wallet address. Once funds are credited to the recipient’s Comearners Investment Account, the transaction becomes irreversible.</p>
                    <p style="font-size: 20px">9.5. If the Investor e-mail address is not registered with us, we will send a notification e-mail to that e­mail address with instructions on how to claim and receive the payment into the destination wallet. If the recipient does not claim the payment within 14 days, the transaction will be cancelled and the funds will be returned to you. You may also cancel the transaction at any time before the funds have been credited to the recipient’s Comearners Investment. To cancel a transaction you should log into your Comearners Investment Account, locate the relevant transaction in your transactions history and select “Cancel”.</p>
                    <p style="font-size: 20px">9.6. You can make recurring payments by setting up a recurring payment order on your Comearners Investment Account. You can cancel your recurring payment order for future payments at any point by logging into your Comearners Investment Account and deleting it. You will not be able to cancel transactions that have already been credited to the recipient.</p>
                    <p style="font-size: 20px">9.7. Payments are subject to payment limits due to security and legal requirements. These limits are set dynamically depending on your verification status. You can view these limits at any time in your Comearners Investment Account profile. You should ensure that your limits are sufficient to cover the payment you intend to make as well as any applicable fees including service fees and currency conversion fees. You should be aware that the recipient of a payment may also be subject to spending and withdrawal limits and that this may affect the recipient’s access to the funds you intend to send.</p>
                    <p style="font-size: 20px">9.8. If we are late in executing a payment that you instruct us to make you may ask us to contact the recipient's payment service provider(Blockchain technology) and ask them to credit it as if it had been received on the correct day.</p>
                    <p style="font-size: 20px">9.9. Sending payments is subject to fees including Cryptocurrencycurrency conversion fees (if applicable) depending on the type of payment you make and the type of Comearners Investment Account you hold. Please see section 13 for details.</p>

                    <h4>9.A Third Party Providers</h4>
                    <p style="font-size: 20px">9.A.1. A Third Party Provider is a service provider that is permitted by law to make payments from your Investment account on your behalf and to provide Crypto currency account information services to you, provided they are acting in accordance with your instructions and the relevant regulatory requirements. You can check whether the provider is authorized in the information they give to you about the services they will provide.</p>
                    <p style="font-size: 20px">9.A.2. We will treat any instruction from a Third Party Provider as if it were from you and the terms of this Agreement will still apply. If you consent to a Third Party Provider having access to information concerning your account, we will assume that you consent to access being granted as frequently as the Third Party Provider requests it.</p>
                    <p style="font-size: 20px">9.A.3. If you give your security details to someone who is not a Third Party Provider, we will have to assume it is you that is authorising us to give access to your account, we will treat payments instructed by that third party as authorized by you and will not be responsible for any losses you suffer as a result of misuse or disclosure of information about your account by that third party.</p>
                    <p style="font-size: 20px">9.A.4 We may refuse to allow a Third Party Provider to access your Cryptogain-mining Account if we are concerned about unauthorised or fraudulent access by that Third Party Provider. Before we do this we will tell you and explain our reasons for doing so, unless it is not reasonably practicable, in which case we will tell you immediately afterwards. In either case, we will tell you using any of the contact details we hold for you. We won’t tell you our reasons where doing so will undermine our reasonable security measures or otherwise be unlawful.</p>
                    <p style="font-size: 20px">If you want to cancel the consent you have given to a Third Party Provider to access your account you should contact them directly.</p>
                    <p style="font-size: 20px">9.A.5 If you think a payment may have been made incorrectly or is unauthorized, you must tell us as soon as possible even where you use a Third Party Provider. If you ask a Third Party Provider to request a payment and they do not do this, we will not be responsible for your payment not being made. Once a Third Party Provider has initiated a payment, you cannot normally cancel it.</p>

                    <h4>10. Making a successful withdrawals and Receiving investment funds.</h4>
                    <p style="font-size: 20px">10.0. For all new investor making first investment withdrawals from your Comearners Accounts, an email will be sent to you immediately requesting you to confirm your personal crypto currency receiving wallet address will be sent to you from support@airlinetrades.com asking for confirmation of your provided crypto currency wallet during registration or if you did not provide a payment method,Note that this message must be replied immediately either by replying the email or contacting our 24/7 live support team to proceed or change of payment details, not until the reply is sent to us we will not approve your first withdrawal and it will remain pending until we get a confirmation letter from you and once this is done we will never ask you for such confirmation again on your next future withdrawals due to clarification to avoid lost of crypto currency into an unknown and unwanted crypto currency wallet. When ever you want to make a change of your crypto currency wallet in the future kindly contact us through again through the support@airlinetrades.com or 24/7 live chat team before making any further withdrawals from your Comearners Investment Account, failure to do so we can never be held responsible for any loss to crypto currency into any unknown or unwanted crypto currency Receiving wallets.</p>
                    <p style="font-size: 20px">10.1. If you receive funds into your Comearners Investment Account, we will send you a notification email and display the payment as a “Receive Money” transaction in your transactions history, together with the date of receipt (the credit value date), the fees charged and, where applicable, any exchange rate used. Each transaction is given a unique transaction ID and shown in the transaction history. We will not alter or amend information displayed in your online transaction history. You should regularly reconcile incoming payments with your own records.</p>
                    <p style="font-size: 20px">10.2. You should be aware that receipt of funds to your Comearners Investment Account does not necessarily mean that these transactions cannot be reversed. We reserve the right to reverse a payment if the payer or the payer’s bank or payment service provider has charged back or otherwise reversed (or is reasonably likely to Charge back or otherwise reverse) an upload or other payment which was used to fund the payment to you.</p>
                    <p style="font-size: 20px">10.3. If a person received a payment notification from us indicating that someone has sent them funds to an email address that is not registered, they will not be credited with the payment until it has been claimed in accordance with the instructions laid out in the notification email. Until then, there will be no contractual or fiduciary relationship between us and the intended recipient. The funds remain those of the sender.</p>
                    <p style="font-size: 20px">10.4. The receipt of payments is subject to fees and Cryptocurrency sending fees, depending on the type of payment you receive and the type Comearners Account you have. Please see section 13 for details.</p>
                    <p style="font-size: 20px"></p>
                    <p style="font-size: 20px"></p>

                    <h4>11. Prohibited Investment transactions</h4>
                    <p style="font-size: 20px">11.1. It is strictly forbidden to make investment and send or receive payments as consideration for the sale or supply of: tobacco products, prescription drugs, drugs and drug paraphernalia, weapons (including without limitation, knives, guns, firearms or ammunition), satellite and cable TV descramblers, material which incites violence, hatred, racism or which is considered obscene, government IDs and licences including replicas and novelty items and any counterfeit products, unlicensed or illegal lotteries or gambling services (including without limitation the use of or participation in illegal gambling houses), unregistered charity services, items which encourage or facilitate illegal activities, prepaid debit cards or other stored value cards that are not associated with a particular merchant and are not limited to purchases of particular products or services, third party processing or payment aggregation products or services, multi-level marketing, pyramid selling or ponzi schemes, matrix programmes or other “get rich quick” schemes or high yield investment programmes, goods or services that infringe the intellectual property rights of a third party, un-coded/miscoded gaming, timeshares or property reservation payments (On and Off Plan). We reserve the right, in our sole discretion, to add categories of prohibited transactions by adding such categories either to these Terms of Use or an acceptable use policy published on the Website.</p>
                    <p style="font-size: 20px">11.2. It is strictly forbidden to make payments to or to receive payments from persons or entities offering illegal gambling services, including (but not limited to) illegal sports betting, casino games and poker games. We may suspend or terminate your Comearners InvestmentAccount at any time or refuse to execute or reverse a transaction if we believe that you directly or indirectly use or have used your Comearners Investment Account for or in connection with illegal gambling transactions. This list is not exhaustive and it is your responsibility to ensure that you do not use our services for transactions that may be considered illegal in your jurisdiction.</p>
                    <p style="font-size: 20px">11.3. You may not use our services if you are residing in certain countries. A list of non-serviced countries is available on the Website and updated from time to time. This list is not exhaustive and we may in our sole discretion decide to discontinue or restrict our services in other countries at any time and without prior notice. We reserve the right to suspend or terminate your Comearners Investment Account at any time if we reasonably believe to be required to do so by law or in order to comply with recommendations issued by a relevant government authority or recognised body for the prevention of financial crime.</p>
                    <p style="font-size: 20px">11.4. It is strictly forbidden to use your Comearners Investment Account for any illegal purposes including but not limited to fraud and money laundering. We will investigate and report any suspicious activity to the relevant law enforcement agency. We reserve the right to charge you in our sole discretion an administration fee as displayed in the "Fees" section of the Website for every investigation we undertake into any such suspicious activity, including where we get notified thereof by any third party whom we partner with. You are prohibited from using your Comearners Investment Account in an attempt to abuse, exploit or circumvent the usage restrictions imposed by a merchant or a Third Party Provider on the services it provides.</p>
                    <p style="font-size: 20px">11.5. You may only accept payments for certain categories of business after approval from us in our sole discretion. Such business categories include but are not limited to: money exchange or remittance businesses, including but not limited to bureaux de change, currency exchanges and purchase of travel money; the collection of any form of donations or payments to charitable or not-for-profit organisations; dealing in natural resources such as jewels, precious metals or stones; live streaming; the sale or supply of alcoholic beverages; the sale of supply of dietary supplements and alternative health products; any other business category published in an acceptable use policy on the Website from time to time. In case you are in doubt whether your business falls under any of the above categories, you must contact Customer Service. We reserve the right in our sole discretion, to add business categories requiring approval by adding such categories either to these Terms of Use or an acceptable use policy published on the Website.</p>
                    <p style="font-size: 20px">11.6. If you conduct or attempt to conduct any transaction in violation of the prohibitions contained in this section 11 or without the necessary approval under section 11.5, we reserve the right to: reverse the transaction; and/or close or suspend your Comearners Investment Account; and/or report the transaction to the relevant law enforcement agency; and/or claim damages from you; and charge you an administration fee as displayed in the "Fees" section of the Website if we apply any of the above.</p>
                    <p style="font-size: 20px">11.7. It is your and not our responsibility to ensure that you only send payments to or receive payments from persons or entities for the sale or supply of goods and services that you may provide or receive in compliance with any applicable laws and regulations. The mere fact that a person or entity accepts payments through us is not an indication of the legality of the supply or provision of their goods and services. If you are in doubt as to the legality of a supply or purchase, you should not continue with your payment.</p>

                    <h4>12. Withdrawing funds</h4>
                    <p style="font-size: 20px">12.1. You can request a withdrawal of all or part of the invest funds and profits held in your Comearners Investment Account at any time. To do this you must log into your Comearners Account and select a withdrawal method and enter the amount to be withdrawn. Withdrawal methods are payment services provided, at least in part, by third party financial institutions (for example, the person Crypto wallet where you hold a Crypto account). We do not guarantee the availability of any particular withdrawal method and may make changes to or discontinue a particular withdrawal method at any time without following the procedure set out in section 17 as long as there is at least one withdrawal method available to you. Where the withdrawal payment is received by you through the involvement of a payment service provider (such as your Crypto wallet where you hold a Crypto account), we shall not be responsible for the withdrawal payment once the withdrawn funds are received by your payment service provider.</p>
                    <p style="font-size: 20px">12.2. Your Comearners Investment Account is subject to withdrawal limits. These limits are adjusted dynamically depending on the type of identification documentation we hold on you. You can view your withdrawal limits at any time in your Comearners Investment Account profile. Before uploading any funds into your Comearners Investment Account, you must ensure that your current withdrawal and spending limits meet your withdrawal and spending requirements as we legally cannot allow you to exceed these limits.</p>
                    <p style="font-size: 20px">12.3. If your withdrawal request exceeds the current limit, we may decline your request and instead require you to send us documents verifying your identity and address prior to allowing a withdrawal of funds or to otherwise cooperate with us to verify your identity.</p>
                    <p style="font-size: 20px">12.4. Withdrawals are subject to fees including Cryptocurrency conversion/sending fees (if applicable). Please see section 13 for details.</p>
                    <p style="font-size: 20px">12.5. For the purposes of a withdrawal transaction, we are a payer and not a payment service provider like the Blockchain technology or any other Crypto currency exchange wallet.</p>
                    <p style="font-size: 20px">12.6. You must not make a withdrawal to a Crypto account or other Payment Method if you are not the named holder and also verified by you I. Your Comearners Accounts. We take any violation of this requirement very seriously and will treat any attempt to use a Payment Method of which you are not the named holder as a fraudulent act. Or you can simply contact the live support when you wish to use Payment wallet which isn't yours.</p>
                    <p style="font-size: 20px">12.7. You must ensure that the payment details you enter when withdrawing funds are correct and your Investment period must be completed before withdrawal can be done. We will not be liable for withdrawn funds being sent to the wrong account where this is due to you providing incorrect payment details.When withdrawing to your Crypto wallet you must ensure that your personal Crypto receiving wallet address is correctly placed and also When withdrawing to a Bank account, you must ensure that the account number, sort code, IBAN and/or BIC/SWIFT are correct. If you have withdrawn funds to the wrong account, you may request that we assist you in reclaiming the funds. However, we will charge you an administration fee as displayed in the "Fees" section of the Website for doing so and we cannot guarantee that the reclaim efforts will be successful.</p>


                    <h4>13. Fees</h4>
                    <p style="font-size: 20px">13.1. Fees depend on whether you are using your Comearners Investment Account for personal or commercial purposes and these can vary depending on the amount you are transacting with us</p>
                    <p style="font-size: 20px">13.2. Transaction related fees can be viewed at any time in the "Fees" section of our Website. Additional fees apply to Comearners Investment Accounts used for commercial purposes in accordance with the applicable terms and conditions referred to in section 4.7 above. You should print or download and keep a copy of the "Fees" section together with a copy of these Terms of Use. For clarity, the "Fees" section forms part of these Terms of Use. Fees are subject to change in accordance with section 17. Under certain circumstances we may charge additional fees as set out in sections 8.3, 8.9, 8.12, 11.6, 12.6 and 12.7.</p>
                    <p style="font-size: 20px">13.3. Your transactions may be subject to currency conversions. If you make a payment from your Comearners Investment Account denominated in one currency to a Comearners Investment Account denominated in another currency, you will be asked to either make the payment in the Cryptocurrency of your Comearners Investment Account or in another Crypto currency. If you choose the Cryptocurrency or fiat currency of your Comearners Investment Account, then the recipient will pay the fee for the conversion into the crypto currency of his or her  Comearners Account. If you choose the cryptocurrency of the Investor Account, you will pay the fee for the conversion into the currency of the payment. If you choose a crypto currency that is neither the crypto currency of your Comearners Account nor the crypto currency of the Comearners Account then you will pay the fee for the conversion into the currency of the payment, and the recipient will pay the fee for the conversion of the payment currency into the crypto currency of his or her Comearners Investment Account.</p>
                    <p style="font-size: 20px"><13.4. For every cryptocurrency conversion, we will apply the average daily interbank market rate published by a third-party foreign currency data provider (Reuters) to which, we add a foreign exchange fee, which is displayed in the "Fees" section of the Website. The foreign exchange fee is payable in addition to the transaction fee. Where we charge fees to you in EUR, we won't apply a foreign exchange fee but will convert the amount in EUR to the currency of your Comearners Investment Account at the applicable wholesale exchange rate./p>
                    <p style="font-size: 20px">13.5. Our Fees are either expressed as a percentage of the transaction or as a fixed amount in EUR. Where fixed fee amounts are displayed in a currency other than EUR, this is for information purposes only. If fees are deducted from a balance or a transaction denominated in a different currency, the EUR fee amount will be converted into an equivalent fee in that other currency based on the Comearners Investment Account wholesale exchange rates applicable at the time and (as displayed on the “Fees" section of the Website under the "Currency Conversion Fees") and then deducted. We will not apply a foreign exchange fee on currency conversions of fees.</p>
                    <p style="font-size: 20px">
                        13.6. Fees payable by you will be deducted from your Comearners Investment Account balance and you hereby authorize us to do the same. Transaction fees will be charged when the transaction is executed. If your Comearners Investment Account balance is insufficient to cover the fees, we may refuse to execute the payment. Reversal or charge back fees will be deducted when incurred.</p>
                    <p style="font-size: 20px">13.7. If the deduction of fees results in a negative Comearners Investment Account balance, you will be required to repay such negative balance by uploading sufficient funds into your Comearners Investment Account. Failure to do so is a breach of these Terms of Use. Repayment of the negative balance is due immediately without notice. However, we reserve the right at any time to send you reminders that you need to upload funds or to take other debt collection measures including but not limited to instructing a debt collection agency or solicitors or to pursue the claim in court. We reserve the right to charge you expenses we have reasonably incurred in connection with any debt collection or enforcement efforts.
                    </p>

                    <h4>14. Your Data</h4>
                    <p style="font-size: 20px">14.1. You explicitly consent to us accessing, processing, and retaining any information you provide to us, for the purposes of providing payment services to you. This does not affect our respective rights and obligations under data protection legislation. You may withdraw this consent by closing your Comearners Investment Account. If you withdraw consent in this way, we will cease using your data for this purpose, but may continue to process your data for other purposes where we have other lawful grounds to do so, such as where we are legally required to keep records of transactions.</p>
                    <p style="font-size: 20px">14.2. The processing of your data is governed by our Privacy Notice which can be found on our Website.</p>

                    <h4>15. Liability</h4>
                    <p style="font-size: 20px">15.1. In the case of an unauthorized payment or a payment that was incorrectly executed due to an error by us, we shall, as soon as practicable, refund the payment amount including all fees deducted therefrom. This shall not apply:</p>
                    <p style="font-size: 20px">15.1.1. where the unauthorized payment arises from your failure to keep the personalized security features of your Comearners Investment Account safe in accordance with section 6 of these Terms of Use, in which case you shall remain liable for the first £35 GBP (or equivalent in the currency of your Comearners Account) unless section 15.1.3 applies;</p>
                    <p style="font-size: 20px">15.1.2. if you fail to notify us without undue delay of any loss of your password or other security features or other event that could reasonably be expected to have compromised the security of your Comearners Investment Account after you have gained knowledge of such event in which case you shall remain liable for losses incurred until you notify us;</p>
                    <p style="font-size: 20px">15.1.3. if the transaction was unauthorized but you have acted fraudulently or compromised the security of your Comearners Investment Account with intent or gross negligence, in which case you shall be solely liable for all losses; or</p>
                    <p style="font-size: 20px">15.1.4. if you fail to dispute and bring the unauthorized or incorrectly executed transaction to our attention within 13 months from the date of the transaction.</p>
                    <p style="font-size: 20px">15.2. Unless you have acted fraudulently, section 15.1.1 shall not apply to transactions made after you have notified us in accordance with section 6.2, where we have failed to provide you with appropriate means for notification or we are required to use strong customer authentication but fail to do so, in which case we shall remain liable and refund any unauthorized transaction to you as soon as practicable.</p>
                    <p style="font-size: 20px">15.3. Without prejudice to the foregoing, you are asked to check the transactions history of your Comearners Investment Account regularly and frequently and to contact Customer Service immediately in case you have any questions or concerns.</p>
                    <p style="font-size: 20px">15.4. In the case of any incorrect or misdirected payment, we shall take reasonable measures to assist you with tracing and recovering such payments.</p>
                    <p style="font-size: 20px">15.5. Subject to the foregoing, we shall not be liable for any disruption or impairment of our service or for disruptions or impairments of intermediary services on which we rely for the performance of our obligations hereunder, provided that such disruption or impairment is due to abnormal and unforeseeable circumstances beyond our reasonable control or the control of the intermediary affected.</p>
                    <p style="font-size: 20px">15.6. We shall not be liable for any indirect or consequential losses including but not limited to loss of profit, loss of business and loss of reputation. We shall not be liable for any losses arising from our compliance with legal and regulatory requirements.</p>
                    <p style="font-size: 20px">15.7. Nothing in these Terms of Use shall operate to exclude liability for death or personal injury due to negligence or for fraud or fraudulent misrepresentation or for any statutory liability that cannot be excluded or amended by agreement between the parties.</p>
                    <p style="font-size: 20px">15.8. Our obligation under these Terms of Use is limited to providing you with an electronic money account and related payment services and we do not make any statement in relation to or endorsement of the quality, safety or legality of any goods or services provided by a Comearners Investment customer or intermediary.</p>
                    <p style="font-size: 20px">15.9. We shall not be liable for the assessment or payment of any taxes, duties or other charges that arise from your use of your Comearners Account or services provided in these Terms of Use.</p>
                    <p style="font-size: 20px">15.10. Reimbursement. You agree to defend, reimburse or compensate us and hold us and our other companies in our corporate group harmless from any claim, demand, expenses or costs (including legal fees, fines or penalties) that we incur or suffer due to or arising out of your or your agents' breach of these Terms of Use, breach of any applicable law or regulation and/or use of the services. This provision shall survive termination of the relationship between you and us.</p>


                    <h4>16. Termination and suspension</h4>
                    <p style="font-size: 20px">16.1. We may terminate your Comearners Investment Account or any payment service associated with it by giving you two months’ prior notice. You may terminate your Comearners Investment Account with us at any time. Different termination provisions may apply if you use your Comearners Investment Account for commercial purposes as set out in section 4.7 above.</p>
                    <p style="font-size: 20px">16.2. Together with a termination notice or at any time thereafter we may give you reasonable instructions on how to withdraw remaining funds.</p>
                    <p style="font-size: 20px">16.3. If your Comearners Investment Account is subject to a reserve, termination of your Comearners Investment Account will not affect our right to hold the reserve and to make deductions therefrom for the time agreed.</p>
                    <p style="font-size: 20px">16.4. We may at any time suspend or terminate your Comearners InvestmentAccount without notice if:</p>
                    <p style="font-size: 20px">16.4.1. you breach any condition of these Terms of Use or any other condition applicable to specific services covered by separate terms and conditions;</p>
                    <p style="font-size: 20px">16.4.2. you violate or we have reason to believe that you are in violation of any law or regulation that is applicable to your use of our services;</p>
                    <p style="font-size: 20px">16.4.3. we have reason to believe that you are in any way involved in any fraudulent activity, money laundering, terrorism financing or other criminal activity; or</p>
                    <p style="font-size: 20px">16.4.4. we have reason to believe that another Comearners Investment Account or Blockchain technology Account provided by us or one of our group companies is held by you and has been used for any fraudulent activity, money laundering, terrorism financing or other criminal activity.</p>
                    <p style="font-size: 20px">16.5. We may suspend your Comearners Investment Account at any time if you don't comply with the the company's policies</p>
                    <p style="font-size: 20px">16.5.1. we reasonably believe that your Account has been compromised or for other security reasons; or</p>
                    <p style="font-size: 20px">16.5.2. we reasonably suspect your Comearners Investment Account to have been used or is being used without your authorisation or fraudulently; and we shall notify you either prior to the suspension or, if prior notification is not possible under the circumstances, promptly after the suspension unless we are prohibited by law to notify you.</p>

                    <h4>17. Changes to these Terms of Use</h4>
                    <p style="font-size: 20px">17.1. These Terms of Use and any additional terms and conditions that may apply are subject to change. Changes will be implemented with prior notice from us under the procedure set forth in this section.</p>
                    <p style="font-size: 20px">17.2. We shall give notice to you of any proposed change by sending an email to the primary email address registered with your Comearners Account.</p>
                    <p style="font-size: 20px">17.3. The proposed change shall come into effect two (2) months after the date the change notice is deemed received under section 18.1, unless you have given us notice that you object to the proposed changes before the changes come into effect. Changes that make these Terms of Use more favourable to you shall come into effect immediately if so stated in the change notice. Changes to exchange rates shall come into effect immediately without notice and you shall not have the right to object to such a change.</p>
                    <p style="font-size: 20px">17.4. If you object to the changes, they will not apply to you. However, any such objection shall constitute a notice by you to terminate and close your Comearners  Account. Your Comearners Account will be closed in accordance with the provisions of section 7 above.</p>

                    <h4>18. How we communicate</h4>
                    <p style="font-size: 20px">18.1. We usually contact you via email. For this purpose you must at all times maintain at least one valid email address in your Comearners Investment Account profile. You are required to check for incoming messages regularly and frequently. Emails may contain links to further communication on our Website. Any communication or notice sent by email will be deemed received by you on the same day if it is received in your email inbox before 4.30 pm on a Business Day. If it is received in your email inbox after 4:30pm on a Business Day or at any other time, it will be deemed received on the next Business Day.
                    </p>
                    <p style="font-size: 20px">18.2. Where legislation requires us to provide information to you on a durable medium, we will either send you an email (with or without attachment) or send you a notification pointing you to information on our Website in a way that enables you to retain the information in print format or other format that can be retained by you permanently for future reference. We recommend you keep copies of all communications we send or make available to you.
                    </p>
                    <p style="font-size: 20px">18.3. You can request a copy of the current Terms of Use or any other contractual document relevant to you by contacting Customer Car Service.</p>
                    <p style="font-size: 20px">18.4. In order to view emails you need a computer with email software that can display emails in HTML format. We may also send you attachments in Adobe Systems Inc.’s Portable Document Format (PDF), for which you need Adobe’s Acrobat Reader, which can be downloaded for free at the Adobe website.</p>
                    <p style="font-size: 20px">18.5. We will never send you any emails with executable files attached or with links to any executable files. If you receive any email with such attachments, you should delete the message without clicking on the attachment. If you are unsure whether a communication is originating from us, please contact Customer Care Service.</p>
                    <p style="font-size: 20px">18.6. We will communicate to you in English and will always accept communications made to us in English. You can choose your preferred language from the list of supported languages in your Comearners Investment Account profile and we will send you automated email notifications and communications regarding changes to these Terms of Use in your chosen language. For non-standard communication, we reserve the right to communicate with you in English. Documents or communications in any other languages are for convenience only and shall not constitute an obligation on us to conduct any further communication in that language.</p>
                    <p style="font-size: 20px">18.7. Apart from communicating via email, we may contact you via letter or telephone, where appropriate. If you use any mobile services, we may communicate with you via SMS. Any communication or notice sent by post will be deemed received three days from the date of posting for UK post or within five days of posting for international post. Any communication or notice sent by SMS will be deemed received the same day.</p>
                    <p style="font-size: 20px">18.8. You may contact us at any time by sending a message to Customer Service via the “Support” facility support@airlinetrades.com</p>

                    <h4>19. Complaints</h4>
                    <p style="font-size: 20px">19.1. Any complaints about us or the services we provide should be addressed to us in the first instance by contacting Customer Service. You should clearly indicate that you are wishing to make a complaint to us. This helps us to distinguish a complaint from a mere query. We send you a complaint acknowledgement by post or by email within 48 hours of receiving your complaint in accordance with our complaints procedure. A copy of our complaints procedure is available here.</p>
                    <p style="font-size: 20px">19.2. We endeavour to provide you with an answer or resolution to your complaint within the time frames as outlined by the Financial Ombudsman Service. Should this not be possible due to unforeseen circumstances or lack of information, we will contact you.</p>
                    <p style="font-size: 20px">19.3. If your complaint is not resolved to your satisfaction, you may contact the Financial Ombudsman Service at Exchange Tower, London, E14 9SR, United Kingdom. For additional contact details you may visit the Website at https://airlinetrades.com</p>

                    <h4>20. Miscellaneous</h4>
                    <p style="font-size: 20px">20.1. No person other than you shall have any rights under these Terms of Use and the provisions of the Contracts (Rights of Third Parties) Act 1999 are expressly excluded.</p>
                    <p style="font-size: 20px">20.2. Your Comearners Investment Account is personal to you and you may not assign any rights under the Terms of Use to any third party.</p>
                    <p style="font-size: 20px">20.3. Your Comearners Investment Account is operated in the United Kingdom and these Terms of Use shall be governed by and interpreted in accordance with the laws of England and Wales. Any dispute under these Terms of Use or otherwise in connection with your Comearners Investment Account shall be brought exclusively in the courts of England and Wales except where prohibited by EU law.</p>
                    <p style="font-size: 20px">20.4. If any part of these Terms of Use is found by a court of competent jurisdiction to be invalid, unlawful or unenforceable then such part shall be severed from the remainder of the Terms of Use, which shall continue to be valid and enforceable to the fullest extent permitted by law.</p>

                    <h4>21. Definitions</h4>
                    <p style="font-size: 20px">Various terms in these Terms of Use have a defined meaning as follows:

                        “Business Day” means any day other than a Saturday or a Sunday or a public or bank holiday in England.

                        “Customer Service” means our customer service, which you can reach by sending a message through the “Support” facility on the website

                        “Fees” means the charges payable by you to us for using our services</p>
                    <p style="font-size: 20px">“Financial Ombudsman Service” means the services provided by the United Kingdom Financial Ombudsman Service, details of which can be found at www.financial-ombudsman.org.uk and who can be contacted at The Financial Ombudsman Service, Exchange Tower, London, E14 9SR, United Kingdom</p>
                    <p style="font-size: 20px">
                        “FCA” means the Financial Conduct Authority of the United Kingdom whose address is 25 The North Colonnade, Canary Wharf, London E14 5HS, United Kingdom; further information on the FCA can be obtained on the FCA’s website at www.fca.org.uk</p>
                    <p style="font-size: 20px">“Payment Method” means Crypto currency transfer or bank transfer if permitted and payment instruments including, but not limited to, credit cards and debit cards.</p>
                    <p style="font-size: 20px">“Privacy Notice” is the Comearners policy governing the processing of personal data which is available on the Website, as may be amended from time to time</p>
                    <p style="font-size: 20px">“Comearners” means Comearners Investment Ltd. (registered number: 4260907762) whose registered office is at Floor 27, 25 Canada Square, London, E14 5LQ, United Kingdom</p>
                    <p style="font-size: 20px">“Comearners ” means the electronic/digital Investment account you open and maintain through Comearners Website</p>
                    <p style="font-size: 20px">“Comearners Website” or “Website” means the website available at https://airlinetrades.com</p>
                    <p style="font-size: 20px">“Terms of Use”, means these Comearners Investment Account Terms of Use, published on the Website and as may be amended from time</p>
                    <p style="font-size: 20px">"Third Party Provider" means a service provider authorized by the Financial Conduct Authority (or other European regulator) who you have agreed can access information or make payments for you from your Comearners Investment Account.
                    </p>
                    <p style="font-size: 20px">“We”, “us”, “our” means Comearners</p>
                    <p style="font-size: 20px">
                        “You”, “your” means you, the natural person or legal entity in whose name the Comearners Investment Account is opened and maintained</p>

                    <h4></h4>
                    <p style="font-size: 20px"></p>

                </div>

            </div>
        </div>
    </div>


@endsection
